FROM registry.centos.org/centos:centos7

LABEL name="AI-Stacks Pipeline Dependency Collector: Python: pip"

COPY collector /opt/rh/thoth/dependency-collector/bin/

CMD /opt/rh/thoth/dependency-collector/bin/collector